language: python

dist: jammy

python:
  - '3.11'


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

# command to run tests
script:
    #- pytest
    - python -m unittest discover -s tests -p "*_test.py"
    - python -m unittest discover -s tests -p "test_*.py"
